// packs.js — built-in curated word packs, free for everyone.
// Each word: { word, phonetic?, meanings:[{partOfSpeech, definition, example}] }
// Packs are browsable in Explore and can be added to the user's own list.

const w = (word, pos, def, ex, phon = '') => ({
  word, phonetic: phon, meanings: [{ partOfSpeech: pos, definition: def, example: ex }],
});

export const PACKS = [
  {
    id: 'refined', title: 'Refined & Elegant', emoji: '🕊️',
    blurb: 'Graceful, literary words to make your writing shine.',
    words: [
      w('gentility', 'noun', 'Social superiority or refined, well-bred manners.', 'She carried herself with quiet gentility.', 'dʒɛnˈtɪlɪti'),
      w('eloquent', 'adjective', 'Fluent or persuasive in speaking or writing.', 'He gave an eloquent speech.', 'ˈɛləkwənt'),
      w('sublime', 'adjective', 'Of such excellence or beauty as to inspire awe.', 'The view from the summit was sublime.', 'səˈblaɪm'),
      w('ephemeral', 'adjective', 'Lasting for a very short time.', 'Fame can be ephemeral.', 'ɪˈfɛm(ə)rəl'),
      w('mellifluous', 'adjective', 'Sweet or musical; pleasant to hear.', 'Her mellifluous voice filled the hall.', 'mɛˈlɪflʊəs'),
      w('opulent', 'adjective', 'Ostentatiously rich and luxurious.', 'They dined in an opulent ballroom.', 'ˈɒpjʊlənt'),
      w('pristine', 'adjective', 'Clean and fresh as if new; unspoiled.', 'The beach was pristine at dawn.', 'ˈprɪstiːn'),
      w('serene', 'adjective', 'Calm, peaceful, and untroubled.', 'A serene smile crossed her face.', 'sɪˈriːn'),
      w('luminous', 'adjective', 'Full of or shedding light; radiant.', 'The moon was luminous over the sea.', 'ˈluːmɪnəs'),
      w('quintessential', 'adjective', 'Representing the most perfect example of a quality.', 'He is the quintessential gentleman.', 'ˌkwɪntɪˈsɛnʃ(ə)l'),
      w('resplendent', 'adjective', 'Attractive and impressive through being richly colourful.', 'She was resplendent in a golden gown.'),
      w('ethereal', 'adjective', 'Extremely delicate and light; heavenly.', 'An ethereal glow lit the mist.'),
      w('exquisite', 'adjective', 'Extremely beautiful and delicate.', 'The lace was of exquisite craftsmanship.'),
      w('sumptuous', 'adjective', 'Splendid and expensive-looking.', 'A sumptuous banquet awaited them.'),
      w('debonair', 'adjective', 'Confident, stylish, and charming.', 'A debonair host greeted every guest.'),
      w('urbane', 'adjective', 'Suave, courteous, and refined in manner.', 'His urbane wit charmed the room.'),
      w('genteel', 'adjective', 'Polite and refined, often affectedly so.', 'They kept up genteel appearances.'),
      w('decorous', 'adjective', 'In keeping with good taste and propriety.', 'A decorous silence fell over the hall.'),
      w('graceful', 'adjective', 'Having elegance of form or movement.', 'The dancer made a graceful turn.'),
      w('immaculate', 'adjective', 'Perfectly clean, neat, or tidy; flawless.', 'His suit was immaculate.'),
    ],
  },
  {
    id: 'emotions', title: 'Emotions', emoji: '💛',
    blurb: 'Name exactly how you feel.',
    words: [
      w('melancholy', 'noun', 'A thoughtful or gentle sadness.', 'A wave of melancholy came with the autumn.', 'ˈmɛlənkəli'),
      w('euphoria', 'noun', 'A feeling of intense happiness and excitement.', 'She felt euphoria as she crossed the line.', 'juːˈfɔːrɪə'),
      w('nostalgia', 'noun', 'A sentimental longing for the past.', 'Old songs fill him with nostalgia.', 'nɒˈstaldʒə'),
      w('apprehension', 'noun', 'Anxiety or unease about the future.', 'She waited with growing apprehension.', 'ˌaprɪˈhɛnʃ(ə)n'),
      w('contentment', 'noun', 'A state of peaceful happiness and satisfaction.', 'He sighed with contentment.', 'kənˈtɛntm(ə)nt'),
      w('resentment', 'noun', 'Bitter indignation at unfair treatment.', 'Years of resentment surfaced.', 'rɪˈzɛntm(ə)nt'),
      w('elation', 'noun', 'Great happiness and exhilaration.', 'The win brought a rush of elation.', 'ɪˈleɪʃ(ə)n'),
      w('serenity', 'noun', 'The state of being calm and peaceful.', 'The garden was a place of serenity.', 'sɪˈrɛnɪti'),
      w('indignation', 'noun', 'Anger at something unjust or unworthy.', 'She spoke with righteous indignation.', 'ˌɪndɪɡˈneɪʃ(ə)n'),
      w('empathy', 'noun', 'The ability to understand and share another’s feelings.', 'A good nurse shows real empathy.', 'ˈɛmpəθi'),
      w('trepidation', 'noun', 'A feeling of fear or nervous anticipation.', 'He opened the letter with trepidation.'),
      w('exhilaration', 'noun', 'A feeling of excitement, happiness, or elation.', 'The ride was pure exhilaration.'),
      w('despondent', 'adjective', 'In low spirits from loss of hope or courage.', 'She grew despondent after the news.'),
      w('wistful', 'adjective', 'Having a vague, sad longing or yearning.', 'He gave a wistful glance at the old house.'),
      w('jubilant', 'adjective', 'Feeling or expressing great happiness.', 'The jubilant crowd cheered.'),
      w('forlorn', 'adjective', 'Pitifully sad and abandoned or lonely.', 'A forlorn dog waited at the gate.'),
      w('sanguine', 'adjective', 'Optimistic, especially in a difficult situation.', 'She stayed sanguine about the outcome.'),
      w('morose', 'adjective', 'Sullen and ill-tempered; gloomy.', 'He sat morose in the corner.'),
      w('ecstatic', 'adjective', 'Feeling or expressing overwhelming happiness.', 'They were ecstatic at the news.'),
      w('dejected', 'adjective', 'Sad and depressed; dispirited.', 'She looked dejected after the loss.'),
    ],
  },
  {
    id: 'people', title: 'Describing People', emoji: '🧑‍🤝‍🧑',
    blurb: 'Words that capture character and personality.',
    words: [
      w('gregarious', 'adjective', 'Fond of company; sociable.', 'Her gregarious nature made her the host.', 'ɡrɪˈɡɛːrɪəs'),
      w('meticulous', 'adjective', 'Showing great attention to detail; very careful.', 'He kept meticulous records.', 'mɪˈtɪkjʊləs'),
      w('candid', 'adjective', 'Truthful and straightforward; frank.', 'I’ll be candid: it needs work.', 'ˈkandɪd'),
      w('tenacious', 'adjective', 'Holding firmly to a purpose; persistent.', 'A tenacious reporter chased the story.', 'tɪˈneɪʃəs'),
      w('aloof', 'adjective', 'Distant, cool, or reserved.', 'He stayed aloof at the party.', 'əˈluːf'),
      w('benevolent', 'adjective', 'Kind, generous, and well-meaning.', 'A benevolent patron funded the school.', 'bɪˈnɛvələnt'),
      w('affable', 'adjective', 'Friendly, good-natured, and easy to talk to.', 'The affable clerk put us at ease.', 'ˈafəb(ə)l'),
      w('obstinate', 'adjective', 'Stubbornly refusing to change one’s mind.', 'He was obstinate about the plan.', 'ˈɒbstɪnət'),
      w('magnanimous', 'adjective', 'Generous or forgiving, especially toward a rival.', 'She was magnanimous in victory.', 'maɡˈnanɪməs'),
      w('diligent', 'adjective', 'Showing steady, careful effort.', 'A diligent student, she never missed class.', 'ˈdɪlɪdʒ(ə)nt'),
      w('garrulous', 'adjective', 'Excessively talkative, especially on trivial matters.', 'A garrulous neighbour kept us an hour.'),
      w('reticent', 'adjective', 'Not revealing one’s thoughts readily; reserved.', 'He was reticent about his past.'),
      w('amiable', 'adjective', 'Having a friendly and pleasant manner.', 'An amiable host welcomed us in.'),
      w('austere', 'adjective', 'Severe or strict in manner or appearance.', 'The judge had an austere expression.'),
      w('brusque', 'adjective', 'Abrupt or blunt to the point of rudeness.', 'Her brusque reply ended the chat.'),
      w('cordial', 'adjective', 'Warm and friendly.', 'They exchanged cordial greetings.'),
      w('fastidious', 'adjective', 'Very attentive to accuracy and detail; hard to please.', 'He is fastidious about his desk.'),
      w('impetuous', 'adjective', 'Acting quickly without thought or care.', 'An impetuous decision cost him dearly.'),
      w('stoic', 'adjective', 'Enduring pain or hardship without showing feelings.', 'She remained stoic through the ordeal.'),
      w('vivacious', 'adjective', 'Attractively lively and animated.', 'A vivacious guest lit up the room.'),
    ],
  },
  {
    id: 'mind', title: 'The Mind & Thinking', emoji: '🧠',
    blurb: 'For ideas, insight, and reflection.',
    words: [
      w('astute', 'adjective', 'Having sharp judgement; shrewd.', 'An astute investor, she saw it coming.', 'əˈstjuːt'),
      w('lucid', 'adjective', 'Expressed clearly; easy to understand.', 'She gave a lucid explanation.', 'ˈluːsɪd'),
      w('pensive', 'adjective', 'Deeply or wistfully thoughtful.', 'He grew pensive at the window.', 'ˈpɛnsɪv'),
      w('discern', 'verb', 'To perceive or recognize clearly.', 'I could just discern a figure in the fog.', 'dɪˈsəːn'),
      w('cognizant', 'adjective', 'Aware of something; having knowledge.', 'Be cognizant of the risks.', 'ˈkɒɡnɪz(ə)nt'),
      w('introspective', 'adjective', 'Examining one’s own thoughts and feelings.', 'A quiet, introspective child.', 'ˌɪntrəˈspɛktɪv'),
      w('sagacious', 'adjective', 'Having keen mental discernment; wise.', 'A sagacious old teacher.', 'səˈɡeɪʃəs'),
      w('intuitive', 'adjective', 'Understood instinctively, without conscious reasoning.', 'She had an intuitive grasp of people.', 'ɪnˈtjuːɪtɪv'),
      w('contemplate', 'verb', 'To think about something deeply and at length.', 'He sat to contemplate his next move.', 'ˈkɒntɛmpleɪt'),
      w('rational', 'adjective', 'Based on reason or logic.', 'Let’s make a rational decision.', 'ˈraʃ(ə)n(ə)l'),
      w('perceptive', 'adjective', 'Having or showing sensitive insight.', 'A perceptive critic noticed the flaw.'),
      w('ponder', 'verb', 'To think carefully about something.', 'She paused to ponder the offer.'),
      w('cerebral', 'adjective', 'Intellectual rather than emotional.', 'His films are cerebral and slow.'),
      w('acumen', 'noun', 'The ability to make good judgements quickly.', 'Her business acumen is remarkable.'),
      w('erudite', 'adjective', 'Having or showing great knowledge; learned.', 'An erudite lecture on Rome.'),
      w('pragmatic', 'adjective', 'Dealing with things practically and realistically.', 'A pragmatic approach to the budget.'),
      w('prudent', 'adjective', 'Acting with care and thought for the future.', 'It was prudent to save some money.'),
      w('scrutinize', 'verb', 'To examine closely and critically.', 'They scrutinized every clause.'),
      w('deduce', 'verb', 'To reach a conclusion by reasoning.', 'From the clues she deduced the truth.'),
      w('conjecture', 'noun', 'An opinion formed on incomplete information.', 'It’s pure conjecture without proof.'),
    ],
  },
  {
    id: 'society', title: 'Society & People', emoji: '🏛️',
    blurb: 'The language of the world around us.',
    words: [
      w('ubiquitous', 'adjective', 'Present or found everywhere.', 'Smartphones are now ubiquitous.', 'juːˈbɪkwɪtəs'),
      w('egalitarian', 'adjective', 'Believing all people are equal.', 'An egalitarian society values fairness.', 'ɪˌɡalɪˈtɛːrɪən'),
      w('autonomy', 'noun', 'The right or state of self-government; independence.', 'The region was granted autonomy.', 'ɔːˈtɒnəmi'),
      w('dissent', 'noun', 'Opinion at odds with what is commonly held.', 'A lone voice of dissent.', 'dɪˈsɛnt'),
      w('conformity', 'noun', 'Behaviour in line with accepted standards.', 'Peer pressure encourages conformity.', 'kənˈfɔːmɪti'),
      w('solidarity', 'noun', 'Unity of feeling or action within a group.', 'The workers stood in solidarity.', 'ˌsɒlɪˈdarɪti'),
      w('reciprocity', 'noun', 'Exchanging things for mutual benefit.', 'Trade depends on reciprocity.', 'ˌrɛsɪˈprɒsɪti'),
      w('prejudice', 'noun', 'A preconceived opinion not based on reason.', 'We must fight prejudice.', 'ˈprɛdʒʊdɪs'),
      w('marginalize', 'verb', 'To treat a person or group as insignificant.', 'The policy marginalized the poor.', 'ˈmɑːdʒɪnəlʌɪz'),
      w('hierarchy', 'noun', 'A system in which people or things are ranked.', 'The company has a strict hierarchy.', 'ˈhʌɪərɑːki'),
      w('bureaucracy', 'noun', 'A system of government or administration by many officials.', 'The permit was lost in bureaucracy.'),
      w('demographic', 'noun', 'A particular sector of a population.', 'The app targets a young demographic.'),
      w('disparity', 'noun', 'A great difference or inequality.', 'There is a wide disparity in wages.'),
      w('cohesion', 'noun', 'The act of forming a united whole.', 'The team lacked cohesion.'),
      w('ostracize', 'verb', 'To exclude someone from a group.', 'He was ostracized for speaking out.'),
      w('assimilate', 'verb', 'To absorb and integrate into a wider group.', 'Newcomers slowly assimilated.'),
      w('hegemony', 'noun', 'Leadership or dominance over others.', 'The empire held regional hegemony.'),
      w('populace', 'noun', 'The general public; ordinary people.', 'The reform pleased the populace.'),
      w('civic', 'adjective', 'Relating to a city or citizens.', 'Voting is a civic duty.'),
      w('discourse', 'noun', 'Written or spoken discussion of a topic.', 'Public discourse grew heated.'),
    ],
  },
  {
    id: 'nature', title: 'Nature & the World', emoji: '🌿',
    blurb: 'Beautiful words for the natural world.',
    words: [
      w('petrichor', 'noun', 'The pleasant, earthy smell after rain.', 'Petrichor rose from the warm pavement.', 'ˈpɛtrɪkɔː'),
      w('verdant', 'adjective', 'Green with growing plants; lush.', 'Verdant hills rolled to the horizon.', 'ˈvəːd(ə)nt'),
      w('tempest', 'noun', 'A violent, windy storm.', 'The ship was tossed by the tempest.', 'ˈtɛmpɪst'),
      w('zephyr', 'noun', 'A soft, gentle breeze.', 'A warm zephyr drifted through the trees.', 'ˈzɛfə'),
      w('halcyon', 'adjective', 'Denoting a peaceful, happy, idyllic period.', 'The halcyon days of summer.', 'ˈhalsɪən'),
      w('arid', 'adjective', 'Very dry; having little rainfall.', 'Cacti thrive in arid deserts.', 'ˈarɪd'),
      w('pastoral', 'adjective', 'Portraying country life in an idealized way.', 'A pastoral scene of sheep and meadows.', 'ˈpast(ə)r(ə)l'),
      w('crepuscular', 'adjective', 'Relating to or resembling twilight.', 'Deer are crepuscular, active at dusk.', 'krɪˈpʌskjʊlə'),
      w('cascade', 'noun', 'A small waterfall; a flow pouring downward.', 'A cascade tumbled over the rocks.', 'kaˈskeɪd'),
      w('luminescent', 'adjective', 'Emitting light not caused by heat; glowing.', 'Luminescent plankton lit the waves.', 'ˌluːmɪˈnɛs(ə)nt'),
      w('bucolic', 'adjective', 'Relating to the pleasant aspects of the countryside.', 'A bucolic village by the river.'),
      w('tumultuous', 'adjective', 'Making a loud, confused noise; turbulent.', 'The tumultuous sea crashed ashore.'),
      w('tranquil', 'adjective', 'Free from disturbance; calm.', 'A tranquil lake at dawn.'),
      w('gale', 'noun', 'A very strong wind.', 'A gale battered the coast.'),
      w('foliage', 'noun', 'The leaves of a plant collectively.', 'Autumn foliage blazed red and gold.'),
      w('meander', 'verb', 'To follow a winding course; wander idly.', 'The river meanders through the valley.'),
      w('undulate', 'verb', 'To move with a smooth wave-like motion.', 'The fields undulate in the breeze.'),
      w('torrent', 'noun', 'A strong, fast-moving stream of water.', 'Rain fell in a torrent.'),
      w('sylvan', 'adjective', 'Relating to woods or forests.', 'A sylvan path wound through the pines.'),
      w('iridescent', 'adjective', 'Showing shifting rainbow colours.', 'The beetle’s iridescent shell shimmered.'),
    ],
  },
  {
    id: 'business', title: 'Business & Work', emoji: '💼',
    blurb: 'Sharpen your professional vocabulary.',
    words: [
      w('entrepreneur', 'noun', 'A person who sets up a business, taking on risk.', 'The entrepreneur launched three startups.'),
      w('incentive', 'noun', 'A thing that motivates or encourages action.', 'Bonuses are a strong incentive.'),
      w('logistics', 'noun', 'The detailed coordination of a complex operation.', 'Shipping logistics can be tricky.'),
      w('stakeholder', 'noun', 'A person with an interest in a business or project.', 'We consulted every stakeholder.'),
      w('remuneration', 'noun', 'Payment for work or services.', 'The role offers generous remuneration.'),
      w('viable', 'adjective', 'Capable of working successfully; feasible.', 'A viable business plan.'),
      w('lucrative', 'adjective', 'Producing a great deal of profit.', 'A lucrative contract.'),
      w('mundane', 'adjective', 'Lacking interest; dull and ordinary.', 'Mundane paperwork filled the day.'),
      w('delegate', 'verb', 'To entrust a task to another person.', 'A good manager knows how to delegate.'),
      w('streamline', 'verb', 'To make more efficient and simpler.', 'We streamlined the checkout process.'),
      w('benchmark', 'noun', 'A standard against which things are compared.', 'Sales set a new benchmark.'),
      w('attrition', 'noun', 'A gradual reduction, as of staff or resources.', 'The team shrank through attrition.'),
      w('morale', 'noun', 'The confidence and spirits of a group.', 'The win lifted team morale.'),
      w('proficient', 'adjective', 'Competent or skilled in doing something.', 'She is proficient in three languages.'),
      w('initiative', 'noun', 'The ability to act independently; a fresh approach.', 'He showed real initiative.'),
      w('quota', 'noun', 'A fixed share or target that must be met.', 'The sales quota was ambitious.'),
      w('tenure', 'noun', 'The holding of a position or property.', 'During her tenure, profits doubled.'),
      w('procurement', 'noun', 'The action of obtaining supplies or services.', 'Procurement handles all vendors.'),
      w('collaborate', 'verb', 'To work jointly with others.', 'Two teams collaborated on the launch.'),
      w('surplus', 'noun', 'An amount left over beyond what is needed.', 'The budget ran a small surplus.'),
    ],
  },
  {
    id: 'science', title: 'Science & Discovery', emoji: '🔬',
    blurb: 'The vocabulary of how the world works.',
    words: [
      w('hypothesis', 'noun', 'A proposed explanation to be tested.', 'They tested the hypothesis in the lab.'),
      w('empirical', 'adjective', 'Based on observation or experiment, not theory.', 'Empirical data backed the claim.'),
      w('catalyst', 'noun', 'Something that speeds up a change or reaction.', 'The result was a catalyst for reform.'),
      w('equilibrium', 'noun', 'A state of balance between forces.', 'The system reached equilibrium.'),
      w('phenomenon', 'noun', 'An observable fact or event.', 'Auroras are a natural phenomenon.'),
      w('correlation', 'noun', 'A mutual relationship between two things.', 'There is a correlation between the two.'),
      w('synthesis', 'noun', 'The combination of parts into a whole.', 'A synthesis of many ideas.'),
      w('anomaly', 'noun', 'Something that deviates from the norm.', 'The reading was an anomaly.'),
      w('inertia', 'noun', 'A tendency to remain unchanged or motionless.', 'It took effort to overcome inertia.'),
      w('entropy', 'noun', 'A measure of disorder or randomness.', 'Entropy tends to increase.'),
      w('viscosity', 'noun', 'A fluid’s resistance to flowing.', 'Honey has high viscosity.'),
      w('spectrum', 'noun', 'A band of related qualities or wavelengths.', 'The full colour spectrum.'),
      w('magnitude', 'noun', 'The great size or extent of something.', 'An earthquake of large magnitude.'),
      w('dormant', 'adjective', 'Temporarily inactive; sleeping.', 'The volcano is dormant, not extinct.'),
      w('volatile', 'adjective', 'Easily evaporated; liable to sudden change.', 'A volatile chemical; a volatile market.'),
      w('permeable', 'adjective', 'Allowing liquids or gases to pass through.', 'The rock is permeable to water.'),
      w('finite', 'adjective', 'Having limits or bounds.', 'We have finite resources.'),
      w('saturate', 'verb', 'To soak or fill completely.', 'Rain saturated the soil.'),
      w('luminosity', 'noun', 'The intrinsic brightness of an object.', 'The star’s luminosity is immense.'),
      w('molecular', 'adjective', 'Relating to molecules.', 'A molecular model of water.'),
    ],
  },
  {
    id: 'sat', title: 'SAT / GRE Power Words', emoji: '🎓',
    blurb: 'High-value words for tests and beyond.',
    words: [
      w('aberration', 'noun', 'A departure from what is normal or expected.', 'The error was a rare aberration.'),
      w('capricious', 'adjective', 'Given to sudden changes of mood or behaviour.', 'A capricious ruler.'),
      w('deleterious', 'adjective', 'Causing harm or damage.', 'A deleterious effect on health.'),
      w('esoteric', 'adjective', 'Understood by only a small, specialized group.', 'Esoteric jargon confused the crowd.'),
      w('insidious', 'adjective', 'Proceeding harmfully in a subtle way.', 'An insidious disease.'),
      w('laconic', 'adjective', 'Using very few words.', 'His laconic reply said it all.'),
      w('munificent', 'adjective', 'Very generous.', 'A munificent donation.'),
      w('nefarious', 'adjective', 'Wicked or criminal.', 'A nefarious scheme.'),
      w('obfuscate', 'verb', 'To make unclear or confusing.', 'The report obfuscated the facts.'),
      w('perfunctory', 'adjective', 'Done with minimal effort, as a routine.', 'A perfunctory nod.'),
      w('quixotic', 'adjective', 'Extremely idealistic; unrealistic.', 'A quixotic crusade.'),
      w('recalcitrant', 'adjective', 'Stubbornly resistant to authority.', 'A recalcitrant student.'),
      w('sycophant', 'noun', 'A person who flatters to gain advantage.', 'The king was surrounded by sycophants.'),
      w('taciturn', 'adjective', 'Reserved or uncommunicative in speech.', 'A taciturn old sailor.'),
      w('vociferous', 'adjective', 'Loud and forceful in expressing opinions.', 'Vociferous protest filled the square.'),
      w('zealous', 'adjective', 'Full of energetic devotion to a cause.', 'A zealous reformer.'),
      w('cacophony', 'noun', 'A harsh, discordant mixture of sounds.', 'A cacophony of car horns.'),
      w('dogmatic', 'adjective', 'Asserting opinions as if unquestionably true.', 'A dogmatic lecturer.'),
      w('ineffable', 'adjective', 'Too great to be expressed in words.', 'Ineffable joy.'),
      w('juxtapose', 'verb', 'To place close together for contrast.', 'The film juxtaposes wealth and poverty.'),
    ],
  },
  {
    id: 'writing', title: 'Art, Words & Writing', emoji: '✒️',
    blurb: 'For readers, writers, and lovers of language.',
    words: [
      w('evocative', 'adjective', 'Bringing strong images or feelings to mind.', 'An evocative description of the sea.'),
      w('poignant', 'adjective', 'Evoking a keen sense of sadness or regret.', 'A poignant farewell.'),
      w('visceral', 'adjective', 'Felt deeply and instinctively rather than reasoned.', 'A visceral reaction of fear.'),
      w('nuance', 'noun', 'A subtle difference in meaning or feeling.', 'Every nuance of her tone mattered.'),
      w('cadence', 'noun', 'A rhythmic flow of sounds or words.', 'The poem’s gentle cadence.'),
      w('metaphor', 'noun', 'A figure of speech applying one thing to another.', 'Time is money is a metaphor.'),
      w('allusion', 'noun', 'An indirect reference to something.', 'An allusion to a Greek myth.'),
      w('vignette', 'noun', 'A brief, evocative description or scene.', 'A vignette of small-town life.'),
      w('lyrical', 'adjective', 'Expressing emotion in a beautiful, songlike way.', 'His lyrical prose.'),
      w('terse', 'adjective', 'Sparing in words; abrupt.', 'A terse, one-line reply.'),
      w('florid', 'adjective', 'Elaborately or excessively ornate.', 'A florid, overwrought style.'),
      w('prose', 'noun', 'Ordinary written language without verse structure.', 'She writes clear, plain prose.'),
      w('satire', 'noun', 'Humour used to expose folly or vice.', 'The play is a sharp satire.'),
      w('aesthetic', 'noun', 'A set of principles of beauty or taste.', 'The design has a minimalist aesthetic.'),
      w('motif', 'noun', 'A recurring theme or element.', 'Water is a motif in the novel.'),
      w('rhetoric', 'noun', 'The art of persuasive speaking or writing.', 'Skilled political rhetoric.'),
      w('connotation', 'noun', 'An idea or feeling a word suggests beyond its literal meaning.', '“Home” has warm connotations.'),
      w('imagery', 'noun', 'Vivid descriptive language.', 'The poem is rich in imagery.'),
      w('anecdote', 'noun', 'A short, interesting story about an incident.', 'She opened with a funny anecdote.'),
      w('verbose', 'adjective', 'Using more words than needed.', 'A verbose, rambling essay.'),
    ],
  },
  {
    id: 'body', title: 'Body & Health', emoji: '🫀',
    blurb: 'Words for the body, wellness, and medicine.',
    words: [
      w('ailment', 'noun', 'A minor illness.', 'A common winter ailment.'),
      w('chronic', 'adjective', 'Persisting for a long time; recurring.', 'A chronic condition.'),
      w('acute', 'adjective', 'Severe and sudden in onset.', 'Acute pain in his side.'),
      w('benign', 'adjective', 'Not harmful; (of a tumour) not cancerous.', 'The growth was benign.'),
      w('malignant', 'adjective', 'Very harmful; (of a tumour) cancerous.', 'A malignant tumour.'),
      w('contagious', 'adjective', 'Spread from one person to another.', 'A highly contagious virus.'),
      w('immunity', 'noun', 'The ability to resist infection.', 'The vaccine builds immunity.'),
      w('metabolism', 'noun', 'The chemical processes that maintain life.', 'Exercise boosts metabolism.'),
      w('dexterity', 'noun', 'Skill in performing tasks, especially with the hands.', 'Surgery demands great dexterity.'),
      w('lethargy', 'noun', 'A lack of energy and enthusiasm.', 'The heat brought on lethargy.'),
      w('robust', 'adjective', 'Strong and healthy; sturdy.', 'A robust immune system.'),
      w('frail', 'adjective', 'Weak and delicate.', 'The frail patient rested.'),
      w('convalesce', 'verb', 'To recover health after illness.', 'She convalesced by the sea.'),
      w('remedy', 'noun', 'A medicine or treatment for a disease.', 'A herbal remedy for coughs.'),
      w('symptom', 'noun', 'A sign that indicates a condition.', 'Fever is a common symptom.'),
      w('respiration', 'noun', 'The process of breathing.', 'Rapid respiration after the run.'),
      w('stamina', 'noun', 'The ability to sustain prolonged effort.', 'Marathons require stamina.'),
      w('nausea', 'noun', 'A feeling of sickness with an urge to vomit.', 'A wave of nausea hit her.'),
      w('posture', 'noun', 'The position in which one holds the body.', 'Good posture prevents back pain.'),
      w('rejuvenate', 'verb', 'To make someone look or feel young again.', 'The holiday rejuvenated him.'),
    ],
  },
  {
    id: 'conflict', title: 'Conflict & Persuasion', emoji: '⚖️',
    blurb: 'Words for argument, power, and diplomacy.',
    words: [
      w('advocate', 'verb', 'To publicly recommend or support.', 'She advocates for reform.'),
      w('coerce', 'verb', 'To persuade by force or threats.', 'He was coerced into signing.'),
      w('concede', 'verb', 'To admit or grant, often reluctantly.', 'He conceded the point.'),
      w('rebuttal', 'noun', 'A statement that contradicts an argument.', 'Her rebuttal was devastating.'),
      w('appease', 'verb', 'To pacify by giving in to demands.', 'They tried to appease the crowd.'),
      w('belligerent', 'adjective', 'Hostile and aggressive.', 'A belligerent tone.'),
      w('diplomacy', 'noun', 'Skill in managing relations tactfully.', 'The crisis called for diplomacy.'),
      w('incite', 'verb', 'To stir up or provoke action.', 'The speech incited a riot.'),
      w('mediate', 'verb', 'To help two sides reach agreement.', 'A neutral party mediated the talks.'),
      w('ultimatum', 'noun', 'A final demand with a threat if refused.', 'They issued an ultimatum.'),
      w('propaganda', 'noun', 'Biased information used to promote a view.', 'Wartime propaganda.'),
      w('placate', 'verb', 'To make someone less angry.', 'He tried to placate his critics.'),
      w('adamant', 'adjective', 'Refusing to be persuaded; unyielding.', 'She was adamant about leaving.'),
      w('defiance', 'noun', 'Open resistance; bold disobedience.', 'An act of defiance.'),
      w('negotiate', 'verb', 'To reach agreement by discussion.', 'They negotiated a truce.'),
      w('provoke', 'verb', 'To stimulate a reaction, often anger.', 'The remark provoked outrage.'),
      w('retaliate', 'verb', 'To make a counterattack.', 'They retaliated with tariffs.'),
      w('subdue', 'verb', 'To bring under control by force.', 'Troops subdued the uprising.'),
      w('vehement', 'adjective', 'Showing strong, forceful feeling.', 'A vehement denial.'),
      w('capitulate', 'verb', 'To surrender or give in.', 'The city capitulated at dawn.'),
    ],
  },
  {
    id: 'money', title: 'Money & Economics', emoji: '💰',
    blurb: 'Talk about wealth, markets, and value.',
    words: [
      w('frugal', 'adjective', 'Sparing or economical with money.', 'A frugal shopper.'),
      w('affluent', 'adjective', 'Having a great deal of money; wealthy.', 'An affluent neighbourhood.'),
      w('austerity', 'noun', 'Strict economy; reduced public spending.', 'A decade of austerity.'),
      w('commodity', 'noun', 'A raw material or product that can be traded.', 'Oil is a key commodity.'),
      w('deficit', 'noun', 'The amount by which spending exceeds income.', 'The budget deficit widened.'),
      w('dividend', 'noun', 'A share of profits paid to shareholders.', 'The stock pays a dividend.'),
      w('inflation', 'noun', 'A general rise in prices over time.', 'Inflation eroded savings.'),
      w('recession', 'noun', 'A period of economic decline.', 'The recession cost many jobs.'),
      w('revenue', 'noun', 'Income, especially of a company or state.', 'Ad revenue doubled.'),
      w('thrifty', 'adjective', 'Using money and resources carefully.', 'A thrifty household.'),
      w('destitute', 'adjective', 'Extremely poor; lacking necessities.', 'The fire left them destitute.'),
      w('prosperous', 'adjective', 'Successful, especially financially.', 'A prosperous merchant.'),
      w('appraise', 'verb', 'To assess the value of something.', 'A jeweller appraised the ring.'),
      w('barter', 'verb', 'To trade goods without using money.', 'They bartered grain for cloth.'),
      w('collateral', 'noun', 'Property pledged as security for a loan.', 'The house served as collateral.'),
      w('liquidate', 'verb', 'To convert assets into cash; wind up a business.', 'They liquidated the stock.'),
      w('monopoly', 'noun', 'Exclusive control of a market.', 'The firm held a monopoly.'),
      w('solvent', 'adjective', 'Having enough money to pay debts.', 'The company is now solvent.'),
      w('squander', 'verb', 'To waste in a reckless way.', 'He squandered his fortune.'),
      w('lavish', 'adjective', 'Rich, elaborate, or extravagant.', 'A lavish spender.'),
    ],
  },
  {
    id: 'time', title: 'Time & Change', emoji: '⏳',
    blurb: 'Describe how things shift, last, and fade.',
    words: [
      w('transient', 'adjective', 'Lasting only a short time.', 'A transient fashion.'),
      w('perpetual', 'adjective', 'Never ending or changing.', 'Perpetual motion.'),
      w('imminent', 'adjective', 'About to happen very soon.', 'A storm is imminent.'),
      w('obsolete', 'adjective', 'No longer in use; outdated.', 'The format is now obsolete.'),
      w('sporadic', 'adjective', 'Occurring at irregular intervals.', 'Sporadic gunfire.'),
      w('gradual', 'adjective', 'Taking place slowly, step by step.', 'A gradual recovery.'),
      w('abrupt', 'adjective', 'Sudden and unexpected.', 'An abrupt end to the meeting.'),
      w('evolve', 'verb', 'To develop gradually.', 'The plan evolved over months.'),
      w('dwindle', 'verb', 'To become steadily smaller.', 'Supplies dwindled to nothing.'),
      w('fluctuate', 'verb', 'To rise and fall irregularly.', 'Prices fluctuate daily.'),
      w('chronological', 'adjective', 'Arranged in order of time.', 'A chronological list of events.'),
      w('concurrent', 'adjective', 'Existing or happening at the same time.', 'Two concurrent projects.'),
      w('interim', 'adjective', 'For the time being; provisional.', 'An interim manager.'),
      w('prolong', 'verb', 'To extend the duration of.', 'Don’t prolong the agony.'),
      w('culminate', 'verb', 'To reach a climax or final point.', 'Years of work culminated in success.'),
      w('cease', 'verb', 'To come or bring to an end.', 'The rain ceased at noon.'),
      w('emerge', 'verb', 'To become apparent or come into view.', 'New facts emerged.'),
      w('revert', 'verb', 'To return to a former state.', 'He reverted to old habits.'),
      w('momentum', 'noun', 'The force gained by a moving object or process.', 'The campaign gained momentum.'),
      w('fleeting', 'adjective', 'Lasting for a very short time.', 'A fleeting glimpse.'),
    ],
  },
  {
    id: 'everyday', title: 'Everyday Upgrades', emoji: '⬆️',
    blurb: 'Simple ideas, said more sharply.',
    words: [
      w('ample', 'adjective', 'More than enough; plentiful.', 'Ample time to finish.'),
      w('blatant', 'adjective', 'Done openly and unashamedly.', 'A blatant lie.'),
      w('concise', 'adjective', 'Giving much information clearly in few words.', 'A concise summary.'),
      w('dubious', 'adjective', 'Doubtful; not to be relied on.', 'A dubious claim.'),
      w('feasible', 'adjective', 'Possible to do easily or conveniently.', 'A feasible plan.'),
      w('vivid', 'adjective', 'Producing strong, clear images.', 'A vivid memory.'),
      w('wary', 'adjective', 'Cautious about possible danger.', 'Wary of strangers.'),
      w('brisk', 'adjective', 'Quick and energetic.', 'A brisk walk.'),
      w('apt', 'adjective', 'Suitable or appropriate; likely to.', 'An apt remark.'),
      w('keen', 'adjective', 'Eager; sharp or perceptive.', 'A keen observer.'),
      w('dire', 'adjective', 'Extremely serious or urgent.', 'Dire consequences.'),
      w('vague', 'adjective', 'Not clearly expressed or defined.', 'A vague answer.'),
      w('novel', 'adjective', 'New and original.', 'A novel idea.'),
      w('sturdy', 'adjective', 'Strongly built; robust.', 'A sturdy table.'),
      w('tedious', 'adjective', 'Too long, slow, or dull.', 'Tedious paperwork.'),
      w('trivial', 'adjective', 'Of little value or importance.', 'A trivial detail.'),
      w('utmost', 'adjective', 'Most extreme; greatest.', 'The utmost care.'),
      w('crucial', 'adjective', 'Decisive or critically important.', 'A crucial decision.'),
      w('evident', 'adjective', 'Clearly seen or understood; obvious.', 'It was evident he was tired.'),
      w('adept', 'adjective', 'Very skilled or proficient.', 'Adept at solving puzzles.'),
    ],
  },
  {
    id: 'impressive', title: 'Impressive & Rare', emoji: '✨',
    blurb: 'Show-stopping words worth knowing.',
    words: [
      w('serendipity', 'noun', 'The occurrence of happy events by chance.', 'Meeting her was pure serendipity.'),
      w('ebullient', 'adjective', 'Cheerful and full of energy.', 'An ebullient host.'),
      w('sonorous', 'adjective', 'Deep, full, and rich in sound.', 'A sonorous voice.'),
      w('effervescent', 'adjective', 'Vivacious and enthusiastic; bubbly.', 'Her effervescent charm.'),
      w('luminary', 'noun', 'A person who inspires or influences others.', 'A luminary in physics.'),
      w('panacea', 'noun', 'A solution for all problems.', 'Money is no panacea.'),
      w('epiphany', 'noun', 'A sudden, striking realization.', 'She had an epiphany about her career.'),
      w('aplomb', 'noun', 'Self-confidence and poise.', 'He handled it with aplomb.'),
      w('verve', 'noun', 'Vigour and spirit, especially in art.', 'She played with verve.'),
      w('panache', 'noun', 'Flamboyant confidence of style.', 'He dressed with panache.'),
      w('finesse', 'noun', 'Delicate skill and refinement.', 'Handled with great finesse.'),
      w('rapport', 'noun', 'A close, harmonious relationship.', 'They built an instant rapport.'),
      w('gravitas', 'noun', 'Dignity, seriousness, or solemnity.', 'The role demands gravitas.'),
      w('eloquence', 'noun', 'Fluent, persuasive speaking or writing.', 'Her eloquence moved the jury.'),
      w('zenith', 'noun', 'The highest point; the peak.', 'At the zenith of his career.'),
      w('juggernaut', 'noun', 'A huge, powerful, unstoppable force.', 'A political juggernaut.'),
      w('catharsis', 'noun', 'The release of strong emotion, bringing relief.', 'The film offers catharsis.'),
      w('euphony', 'noun', 'The quality of being pleasing to the ear.', 'The euphony of the verse.'),
      w('wanderlust', 'noun', 'A strong desire to travel.', 'Wanderlust took her abroad.'),
      w('zeitgeist', 'noun', 'The defining spirit or mood of a period.', 'The film captured the zeitgeist.'),
    ],
  },
  {
    id: 'grabbag', title: 'Grab Bag', emoji: '🎒',
    blurb: 'Great words that don’t fit a box — just learn them.',
    words: [
      w('quandary', 'noun', 'A state of uncertainty over what to do.', 'She was in a quandary about the offer.'),
      w('plethora', 'noun', 'A very large amount; an excess.', 'A plethora of options.'),
      w('myriad', 'noun', 'A countless or very great number.', 'A myriad of stars.'),
      w('tangible', 'adjective', 'Perceptible by touch; real and concrete.', 'Tangible proof.'),
      w('ambiguous', 'adjective', 'Open to more than one interpretation.', 'An ambiguous reply.'),
      w('inevitable', 'adjective', 'Certain to happen; unavoidable.', 'Change is inevitable.'),
      w('resilient', 'adjective', 'Able to recover quickly from difficulties.', 'A resilient community.'),
      w('versatile', 'adjective', 'Able to adapt to many functions.', 'A versatile tool.'),
      w('spontaneous', 'adjective', 'Done from natural impulse, unplanned.', 'A spontaneous trip.'),
      w('elaborate', 'adjective', 'Involving many carefully arranged parts.', 'An elaborate plan.'),
      w('profound', 'adjective', 'Very great; showing deep insight.', 'A profound effect.'),
      w('subtle', 'adjective', 'So delicate as to be hard to notice.', 'A subtle hint.'),
      w('intricate', 'adjective', 'Very complicated or detailed.', 'An intricate design.'),
      w('coherent', 'adjective', 'Logical and consistent.', 'A coherent argument.'),
      w('arbitrary', 'adjective', 'Based on random choice, not reason.', 'An arbitrary rule.'),
      w('notorious', 'adjective', 'Famous for something bad.', 'A notorious outlaw.'),
      w('ambivalent', 'adjective', 'Having mixed feelings about something.', 'She felt ambivalent about moving.'),
      w('candor', 'noun', 'The quality of being open and honest.', 'I admire his candor.'),
      w('deft', 'adjective', 'Neatly skilful and quick.', 'A deft touch.'),
      w('paradox', 'noun', 'A seemingly contradictory but true statement.', 'A curious paradox.'),
      w('scrutiny', 'noun', 'Critical, close observation.', 'Under public scrutiny.'),
      w('paramount', 'adjective', 'More important than anything else.', 'Safety is paramount.'),
      w('inherent', 'adjective', 'Existing as a natural, permanent quality.', 'An inherent risk.'),
      w('tangential', 'adjective', 'Only slightly relevant.', 'A tangential remark.'),
      w('superfluous', 'adjective', 'More than is needed; unnecessary.', 'Cut the superfluous words.'),
      w('ostensible', 'adjective', 'Stated as true but perhaps not so.', 'The ostensible reason.'),
      w('tenuous', 'adjective', 'Very weak or slight.', 'A tenuous connection.'),
      w('salient', 'adjective', 'Most noticeable or important.', 'The salient points.'),
      w('cogent', 'adjective', 'Clear, logical, and convincing.', 'A cogent argument.'),
      w('succinct', 'adjective', 'Briefly and clearly expressed.', 'A succinct summary.'),
    ],
  },
];

export function getPack(id) {
  return PACKS.find((p) => p.id === id) || null;
}
